### ISSUE TITLE
Could define transitions semantically

### ISSUE THREAD

**Issue by ianvollick** [WICG/shared-element-transitions#11]
Current explainer suggests a fixed set of transitions with names like "reveal-left" or "cover-right". If we were to, instead, have "next-horizontal", "next-vertical", "next-in-stack" (and similar for "prev-"), I think it'd have a number of benefits. It'd allow the UA to
- Ensure that effects align with platform idioms (and evolve as these idioms change), and
- Ensure consistent semantics making it easier to understand what's happening (eg, next- may be left or right depending on locale).

**Comment by jeremyroman** [comment]
Localization will need to be resolved with this approach, since which direction is "next" may vary by locale (e.g., I believe RTL languages like Arabic and Hebrew often use opposite directions to English). We'd also need to decide whether these should match the locale of the browser, of the previous document, or of the next document, since these may all be different.

There are also writing modes that lay out text vertically rather than horizontally, though I don't know how well-supported they are on the web in practice as it is.

**Comment by ianvollick** [comment]
I'm leaning toward browser locale. This would let prev-horizontal consistently align with the direction of browser's back (I've tried switching system language to Hebrew on iOS and Android and back seemed to flip direction). I think it'd become complex if it were related to content (as you mentioned, it's not clear which content would drive the direction), and I think the consistency of matching the browser locale would help reinforce the semantics of next/prev.

**Comment by Malvoz** [comment]
[CSS Logical Properties](https://www.w3.org/TR/css-logical/) describes flow-relative properties, so instead of "next-horizontal", "next-vertical", etc., maybe the transitions' names could be:

```diff
- reveal-left
+ reveal-inline-start
- reveal-right
+ reveal-inline-end
- reveal-up
+ reveal-block-start
- reveal-down
+ reveal-block-end
- cover-left
+ cover-inline-start
- cover-right
+ cover-inline-end
- cover-up
+ cover-block-start
- cover-down
+ cover-block-end
```

**Comment by jeremyroman** [comment]
> I'm leaning toward browser locale. This would let prev-horizontal consistently align with the direction of browser's back (I've tried switching system language to Hebrew on iOS and Android and back seemed to flip direction). I think it'd become complex if it were related to content (as you mentioned, it's not clear which content would drive the direction), and I think the consistency of matching the browser locale would help reinforce the semantics of next/prev.

This might be the best option, but it may introduce inconsistency between the direction of authored effects within the page (which presumably match the locale of the document) and browser-provided effects. Obviously this will always exist at some level, but it's also worth considering whether we want to offer only browser-directional effects or also offer effects which respect the directionality of the document asking for it, or even explicit directionality.

**Comment by khushalsagar** [comment]
The final API expresses default transitions using CSS.
