### ISSUE TITLE
Should we switch to 'id' instead of 'tag', making it unique?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#111]
I pushed for it being a 'tag' since it seemed to fit better with CSS, and allowed for cases like sharing each comment, but it complicates the selectors, and matching them in DOM order isn't always the right order (eg chat messages where the last item is the latest item).

**Comment by khushalsagar** [comment]
We enforce that the page-transition-tag should be unique which also makes it easy to match elements between the 2 DOMs.
