### ISSUE TITLE
The API seems extremely hard to debug

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#119]
I don't know if it's just me, but I find writing a test and figuring out what curves are being used by default next to impossible.

Even knowing whether the :transition-container pseudo is using a transform or left/top or anything else for positioning is not at all obvious.

Am I missing a technique that's commonly used here?

**Comment by chrishtr** [comment]
Can you give an example of what you were trying to do? I'm not totally sure I understand.

**Comment by vmpstr** [comment]
Just setting up customization, it'd be nice to know what i'm adding vs what i'm overriding. I have a linear default transition on 
::transition-container(foo), so now I want to make it do a different path from start to end (a curved path), so I can add some keyframes.. But what's my start/end? I don't really know.

I don't know, I guess I'm just confused about what I can or should even change here, since nothing shows up in devtools or anywhere else, I simply have to know what element to target and how to update its behavior

**Comment by chrishtr** [comment]
if it's just a curved path between the same endpoints, then is that expressible in an easing function?

**Comment by vmpstr** [comment]
I don't think an easing function will help. I guess if we have enough documentation it's fine? I just don't think the customization right now is easy to do... Maybe we need to prioritize devtools support.

I'm closing this for now
