### ISSUE TITLE
transition.prepare() timing attacks

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#12]
Could the resolve time of `transition.prepare()` reveal anything about the content? Particularly in cases where the texture would include iframed content.

**Comment by vmpstr** [comment]
I don't think prepare can reveal anything about the content that would not already be discoverable by rAF timing. In other words, the extra step added to prepare is to readback the texture that we have presented. The presentation cost itself can vary depending on content, but the presentation happens with or without our API. The texture readback should be a constant time overhead (again not revealing anything extra about the content)

**Comment by khushalsagar** [comment]
I think this can be resolved. The prepare step doesn't enable any timing attacks. Adding a bit more implementation detail to this to ensure we aren't missing a subtlety. This is how the snapshot logic is executed :

1) We draw the element's content to a render pass (texture) as a part of the default rendering update done by the compositor. Promoting an element to a render pass can be done by triggering compositing hints and effects with existing web APIs.

2) If this is a shared element, we retain this render pass (either the original or a copy). And then use it for rendering the current frame as usual. At most, the prepare step is introducing a texture copy in addition to the existing rendering update steps.
