### ISSUE TITLE
transition-{old,new}-content animation-duration: inherit?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#121]
I find that when I'm customizing the animation and I want to set a different duration, I have to set it on transition-container, transition-old-content and transition-new-content. I propose that we set the transition-old-content and transition-new-content to inherit, since I think it's going to be a much more common case to have durations match for all three.

**Comment by jakearchibald** [comment]
Agreed.

There may be other things we want to do this with, such as animation delay, easing, and animation fill.

**Comment by khushalsagar** [comment]
The above PR will address this.
