### ISSUE TITLE
page-transition vs document-transition vs something else

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#122]
I wanted to mention "page" vs "document" terminology. Our new API has a `::page-transition` prefix for the pseudo elements generated (`::page-transition-image-wrapper(page-transition-tag)`, `::page-transition-outgoing-image(page-transition-tag)`, 
`::page-transition-incoming-image(page-transition-tag)`, etc).

A page sounds like something that includes all of the content including content inside iframes (and at least in Blink internals, that's also represented by a `Page` object). `Document` on the other hand is a per iframe object.

I wanted to make sure that 
1. We do want independent transitions inside iframes, and
2. We are still sticking to page-transition as terminology (as opposed to something like `document-transition`)

**Comment by jakearchibald** [comment]
I'm happy switching to `document`. There are super weird cases where we change `document` but _don't_ change `window`, so yeah, scoping this to `document` makes sense.

There was talk a while ago about allowing items inside an iframe to be part of the parent's transition. I'm not sure it's something we should bother with, but if they're still keen on it, we need to figure out how it fits in with this

**Comment by vmpstr** [comment]
I think designing the API that leaves room to extend to iframes makes sense to me, although I am not in a rush to implement that :)

**Comment by khushalsagar** [comment]
We'll have a session (likely next week) to bike shed on naming. Can discuss these there.
