### ISSUE TITLE
it may be hard to support mix-blend-mode in captures

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#124]
I think there are some effects like mix-blend-mode or backdrop-filter that are pretty hard to capture.

Not sure if it's important.

**Comment by vmpstr** [comment]
* The shared element might need to be a backdrop filter root: https://drafts.fxtf.org/filter-effects-2/#BackdropRoot

* have isolation: isolate

* shared element's mix blend mode and backdrop filter don't apply

**Comment by khushalsagar** [comment]
The details for snapshoting have been spec'd now. Effects like mix-blend-mode and backdrop-filter which are relevant when the element is drawn into its target stacking context are ignored, similar to the CSS element() function.
