### ISSUE TITLE
mode 2 shared element's opacity

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#125]
In the mode where we take the shared element's own styles and apply them to the pseudo (to be able to interpolate them) do we do that with opacity as well? The reason I ask is that opacity is a part of the default transition, so it becomes unclear which style take priority -- the source one or the transition one.

I think the "right" solution is to have both: opacity would be baked into the snapshot regardless of which mode we're in, but maybe there are cases that I'm missing where we need to override it

**Comment by khushalsagar** [comment]
Closing this for now. We need to clearly define the base setup for how this capture mode will work before diving into these details.
