### ISSUE TITLE
callback timing for createDocumentTransition.

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#126]
`createDocumentTransition` takes a callback which does most of the work of setting the transition up. It doesn't specify when the callback is actually invoked. I don't know know if it's important, but we should at least make a note.

**Comment by vmpstr** [comment]
There are some potential issues with having a single callback to set up and control the transition. Specifically, we don't know whether start will still be called since this is an async callback. Consider:

```js
document.createDocumentTransition((t) => {
  t.captureAndHold().then(async () => {
     await changeTheDom();
     requestAnimationFrame(() => t.start());
  });
});
```

I don't think we can know if or when the start will be called, so we don't know if we should hold on to the transition or abandon it at some point.

I think a better approach might be two callbacks: first to set the shared elements for the capture phase, then captureAndHold is implicitly called between the two callbacks, then the second callback is only to change the dom and set up the shared elements for the start phase. Start would be implicitly called after the second callback finishes.

**Comment by khushalsagar** [comment]
The spec'd API clearly outlines timing of callbacks now.
