### ISSUE TITLE
createDocumentTransition technically allows for multiple transitions

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#127]
The way the API is meant to be used, we could call createDocumentTransition multiple times and start multiple transitions. However, that makes it unclear what happens with the pseudo element tree (since there is only one).

For now, I'd prefer that we limit this to one transition at a time, but we can also think about what we could do with the pseudo element tree. The transition really only indicates which elements are captured and which elements are participating in the transition, so we could reuse the same pseudo element tree

**Comment by vmpstr** [comment]
Basically, there are implementation difficulties with multiple transitions. E.g. ownership of the pseudo element tree has to be shared

**Comment by jakearchibald** [comment]
Related: https://github.com/WICG/shared-element-transitions/issues/52

**Comment by khushalsagar** [comment]
The spec clarifies how we deal with a trigger for concurrent transitions. Supporting multiple of these on independent DOM sub-trees is out of scope for v1.
