### ISSUE TITLE
Is transition.ignoreCSSTaggedElements sticky?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#131]
Once we call `transition.ignoreCSSTaggedElements()`, does that mean it's just the next call to `captureAndHold()` or `start()` that is affected, or all subsequent calls?

**Comment by vmpstr** [comment]
I propose that if called, then all subsequent function calls that would use elements ignore css. We need to also know when to "reset" this, but that's presumably tied to the duration of the createDocumentTransition callback.

**Comment by khushalsagar** [comment]
ignoreCSSTaggedElements is not a thing anymore.
