### ISSUE TITLE
Is root always captured, or does it need to be explicitly specified

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#132]
From the explainer:

```js
:root {
  page-transition-tag: root;
}
```

Is this a required style? I was under the impression that the root is always captured

**Comment by vmpstr** [comment]
I propose that the root is always captured, since that's basically what we have set up. And also reserving the `root` keyword for that

**Comment by vmpstr** [comment]
From sync: We can capture the root by default with an opt-out, and making the root tag reserved sg

**Comment by jakearchibald** [comment]
What does that mean for MPA? Doesn't it mean every navigation will have a transition by default?

**Comment by khushalsagar** [comment]
We can make root capture optional for MPA too. If you know only a small part of the page is gonna change for example.

It'll work because the transition is orchestrated on top of paint holding.
