### ISSUE TITLE
Proposal: animation-fill-mode: forwards for default animations.

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#134]
Since different shared elements can have different transition durations, we should do a forwards animation fill

**Comment by jakearchibald** [comment]
I usually advise against fill forward, but since these elements are going away at the end of the transition, it seems like the best thing to do.

It's probably best to fill both, to handle animation delays too.

**Comment by khushalsagar** [comment]
The UA CSS uses both.
