### ISSUE TITLE
'none' should be a reserved tag

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#138]
Since we're adding a CSS property to tag elements, it needs to have a default value. I propose that default is 'none', which makes it not a valid tag (and we should not allow it in JS api either to avoid confusion). We should reflect that in the explainer.

**Comment by jakearchibald** [comment]
Agreed

**Comment by jakearchibald** [comment]
Should the same apply to "unset" and "initial"?

**Comment by vmpstr** [comment]
Yes, I think that's also true (and inherit). The way we specified this is that this is custom-ident, which already forbids CSS-wide keywords (from https://www.w3.org/TR/css-values-4/#custom-idents), and "unset" "initial" and "inherit" seem to qualify under that.

I think this is good to say for the explainer, but from the spec perspective, i don't think we need any special mention

**Comment by jakearchibald** [comment]
This is addressed in the spec.
