### ISSUE TITLE
Fix `nextUrl` casing in `explainer.md`

### ISSUE THREAD

**Issue by gustavopch** [WICG/shared-element-transitions#150]
AFAIK, acronyms are usually uppercased (e.g. `JSON`, `toDataURL`, `innerHTML`), so `nextUrl` should be changed to `nextURL` here:
https://github.com/WICG/shared-element-transitions/blob/bcf2ddd556b87eafc0e5353e5be02230ae4a73d5/explainer.md?plain=1#L500

As a matter of fact, it's already uppercased in this other occurrence:
https://github.com/WICG/shared-element-transitions/blob/bcf2ddd556b87eafc0e5353e5be02230ae4a73d5/explainer.md?plain=1#L459

**Comment by khushalsagar** [comment]
The latest update to the explainer doesn't have the API referenced above.
