### ISSUE TITLE
API Design: Sharing SPA elements

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#16]
We need to figuring out an elegant way to identify shared elements (for SPA cases) so that we can transition between them.

My proposal is to have the prepare() call and start() calls take an array of elements, representing the "before" and corresponding "after" elements.

For example,
```js
prepare({ rootTransition: "reveal-up", duration: 300, sharedElements: [e1, e2] });
...
start({ sharedElements: [e1, anotherE] });
```

Here, the transition happens and e1 from the saved frame matches with e1 from the latest frame, and e2 from the saved frame matches with anotherE from the latest frame.

Alternatively, we could give these elements names like
```js
prepare({ ..., sharedElements: { "static hero": e1, "avatar": e2 }});
```

That would make it easier to remember the order but it is more verbose and prone to more typos

**Comment by tomayac** [comment]
I'd rather see an explicit mapping, maybe something like this:

```js
await document.documentTransition.prepare({
    rootTransition: 'cover-up',
    sharedElements: [
      {
        from: elem1,
        to: elem1,
      },
      {
        from: elem2,
        to: elem4,
      },
    ],
  },
});

updateDOMForSettingsPage();

await document.documentTransition.start();
```

Having this depend on array order seems like a suboptimal developer experience to me personally.

**Comment by khushalsagar** [comment]
Thanks for the feedback! We're still iterating on the API shape and the new proposal actually aligns with what you mentioned above. Could you take a look at https://github.com/WICG/shared-element-transitions/blob/main/feature_details.md

**Comment by pavsidhu** [comment]
@tomayac Completely agree with the premise and that arrays are not the right solution. However how would you have access for the `to`s before calling `updateDOMForSettingsPage()`?

**Comment by khushalsagar** [comment]
@pavsidhu, what's your take on the idea here : https://github.com/WICG/shared-element-transitions/blob/main/feature_details.md#referencing-elements. We've been thinking about how to allow scripted control of these transitions for MPAs. You can see the use-cases under "Sample Code" in that doc for where this control could be useful.

To solve the problem you mentioned, we're introducing a placeholder for captured elements from the previous page that you can reference in the new page. The "Single Page App API" also aligns with this idea.

**Comment by tomayac** [comment]
> @tomayac Completely agree with the premise and that arrays are not the right solution. However how would you have access to the `to`s before calling `updateDOMForSettingsPage()`?

Hah, right. I didn't realize this. 

> As verbose as using an object to reference elements is, this may match up better with the [multi-page app CSS API discussed here](https://github.com/WICG/shared-element-transitions/issues/2#issuecomment-826952871) where a `nav-transition-id` has been proposed.

Yeah, I think something like `nav-transition-id` could make sense.

**Comment by khushalsagar** [comment]
Resolved in the final API with page-transition-tag.
