### ISSUE TITLE
Explainer & spec inconsistent w.r.t cross-origin transisions

### ISSUE THREAD

**Issue by Sauski** [WICG/shared-element-transitions#162]
Hi Folks,

The explainer contains the following:

> Cross-origin transitions are something we want to tackle, but may have significant differences and restrictions for security reasons. Cross-origin transitions are not covered in this document.

Excluding cross-origin transitions from the current scope makes sense, they'll certainly be more challenging than same-origin transitions, and require greater privacy & security consideration.

My concern is that, at least by my reading, the specification doesn't attempt to make the same distinction - it makes no reference to any cross origin distinctions. 

What's the plan w.r.t to the specification and cross origin transitions? If the team doesn't have a plan, or isn't ready for privacy / security input into cross origin scenarios, it makes sense to explicitly exclude them in the specification.

Theo.

**Comment by khushalsagar** [comment]
The spec is up now and cross-origin is not mentioned there.
