### ISSUE TITLE
Allow using WA-API for nested pseudo elements

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#163]
Currently pseudo elements created for a transition use the documentElement as the originating element. This allows them to be targeted easily in both css and script APIs (like WA-API and getComputedStyle). We plan to switch this to have each pseudo element originate from its immediate ancestor element in the DOM tree. This requires a change both to target them in CSS and in the script API.

An open [issue](https://github.com/w3c/csswg-drafts/issues/7346) addresses the gap to make it easier to target them with CSS. Filing this issue to follow up with a change in the script API once the CSS issue is resolved. The long term plan is to use CSSPseudoElement to make script access of these elements similar to DOM elements. In the short term we can add a `pseudoSelector` (similar to `pseudoElement`) which allows using a selector to target nested pseudo elements.

@jakearchibald @vmpstr

**Comment by khushalsagar** [comment]
Resolved in the external issue.

**Comment by jakearchibald** [comment]
External issue: https://github.com/w3c/csswg-drafts/issues/7469
