### ISSUE TITLE
Switch to layout containment instead of paint containment for shared elements

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#164]
The SET spec requires shared elements to have paint containment. This is necessary for 2 reasons:

- So the elements generate a stacking context which makes it easier to capture their contents as an atomic screenshot.

- So the elements are a containing block for all positioned descendants. This is necessary because during the transition they animate as an atomic unit.

Both of these should be possible with just layout containment so paint containment adds unnecessary additional constraints.

**Comment by vmpstr** [comment]
Done.
