### ISSUE TITLE
Should prepare's callback always be called?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#169]
From the steps in https://tabatkins.github.io/specs/css-shared-element-transitions/#dom-samedocumenttransition-prepare, there are some early exits. For instance, if there's already a transition running.

```js
function onSomeButtonPress() {
  if (!self.SameDocumentTransition) {
    showArticle();
    return;
  }

  const transition = new SameDocumentTransition();
  transition.prepare(() => showArticle());
}
```

In this case, the article will fail to show if there's already a transition in progress. This is because `prepare` will reject early, without calling the callback.

This seems like a gotcha, as it might not happen in testing, but will happen in live. Also, there's no way to defend against this…

```js
async function onSomeButtonPress() {
  if (!self.SameDocumentTransition) {
    showArticle();
    return;
  }

  const transition = new SameDocumentTransition();

  try {
    await transition.prepare(() => showArticle());
  } catch (err) {
    showArticle();
  }
}
```

This doesn't work around the issue, as `prepare` might also reject after the callback is called, so it'd get called twice. So I guess we're asking developers to do this:

```js
async function onSomeButtonPress() {
  if (!self.SameDocumentTransition) {
    showArticle();
    return;
  }

  const transition = new SameDocumentTransition();
  let prepareCallbackCalled = false;

  try {
    await transition.prepare(() => {
      prepareCallbackCalled = true;
      showArticle();
    });
  } catch (err) {
    if (!prepareCallbackCalled) showArticle();
  }
}
```

…and that's a lot just to get reliable behaviour.

---

Transitions are an enhancement to the DOM change. If the transition doesn't happen, that's sad but ok. If the DOM change doesn't happen, that's a totally broken experience.

I don't think we should break the DOM change because the transition cannot happen.

I propose we _always_ call the callback passed to `prepare`. The returned promise can still reject if preparation of the transition fails.

We should consider aborting the previous transition in favour of the new one, rather than failing the new one, but that's a different question.

**Comment by khushalsagar** [comment]
> as prepare might also reject after the callback is called

When do we hit this case? If the promise returned by prepare is rejected with an exception?

> We should consider aborting the previous transition in favour of the new one, rather than failing the new one, but that's a different question.

I think its related since one of the cases where we currently throw an exception without dispatching the callback is when a transition is in progress. It will also be unexpected behaviour if we dispatch the callback while another transition is in progress and as a result the DOM completely changes.

If the idea is that anytime prepare is called a DOM change must happen (with or without a transition), then we should abort the previous transition in this case and start a new one.

**Comment by jakearchibald** [comment]
> > as prepare might also reject after the callback is called
> 
> When do we hit this case? If the promise returned by prepare is rejected with an exception?

Yep! One place is:

> If multiple elements or pseudo-elements on the Document have the same [page transition tag](https://tabatkins.github.io/specs/css-shared-element-transitions/#page-transition-tag), [abandon the page transition](https://tabatkins.github.io/specs/css-shared-element-transitions/#abandon-the-page-transition) managed by [this](https://webidl.spec.whatwg.org/#this) with an InvalidStateException.

---

> If the idea is that anytime prepare is called a DOM change must happen (with or without a transition), then we should abort the previous transition in this case and start a new one.

Yeah, I think that's the best option.

**Comment by jakearchibald** [comment]
Something I noticed while working on the spec:

Feels like we should avoid resolving the promise returned by `prepare` before the callback has settled.

**Comment by jakearchibald** [comment]
We agreed that, in cases where the DOM change makes sense, but a transition is impossible due to misconfiguration, we should still call the prepare callback.

There's still the question of when the `prepare` promise should reject, but I'll create another issue for that.
