### ISSUE TITLE
Define painted rect for shared element snapshots.

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#17]
When we identify shared elements, we should ensure they have paint containment to better understand the bounds of the animation. It should also work with replaced elements, such as imgs.

**Comment by khushalsagar** [comment]
Currently we're doing this using contain:paint which clips the element's snapshot to its border box and allows an explicit overflow using overflow-clip-margin. We'll likely still need an upper cap in case the element has very large bounds. Especially if we don't have any ancestor clips (including the viewport clip).

**Comment by khushalsagar** [comment]
Defined in the [spec](https://tabatkins.github.io/specs/css-shared-element-transitions/#computing-the-interest-rectangle) now. #185 is tracking the TODO for defining what is captured if we must clip the snapshot.
