### ISSUE TITLE
Behaviour of not-rendered elements

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#170]
When we look for elements to transition, it feels like we should ignore not-rendered elements.

For example, I think creating a transition from:

```html
<div style="page-transition-tag: foo">hello</div>
<div style="page-transition-tag: foo; display: none">world</div>
```

…to:

```html
<div style="page-transition-tag: foo; display: none">hello</div>
<div style="page-transition-tag: foo">world</div>
```

…should be valid. As in, it shouldn't fail due to the repeated use of `page-transition-tag: foo`, since only one of them is renderable.

This also means we wouldn't create transition pseudo-elements for elements that are not-rendered on both sides of the transition. 

As in, a transition from:

```html
<div style="page-transition-tag: foo; display: none">hello</div>
```

…to:

```html
<div style="page-transition-tag: foo; display: none">world</div>
```

…would not create `::page-transition-container(foo)`.

This seems to fit in with the model where we don't create CSS animations for not-rendered elements.

**Comment by khushalsagar** [comment]
The spec has been updated to ignore such elements, as if they were not tagged. Note that if the not rendered state changes midway through a transition then we still consider the tag on this element.
