### ISSUE TITLE
Should transition instances be reusable?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#173]
```js
const transition = new SameDocumentTransition();
transition.prepare(callback);
await transition.finished;

// Should this work:
transition.prepare(differentCallback);
```

My gut feeling is that one `SameDocumentTransition` instance should be used for one same document transition. 

However, `Animation` objects can be restarted once they're complete, and can even have their target & keyframes modified. For example, their `finished` promise changes when the animation is cancelled, or changes from a 'finished' state to a 'not-finished' state.

However I'm not sure this model makes sense here. `SameDocumentTransition`s are meant to be a transition between states, whereas animations can be ongoing within a single state.

Maybe this points to a bigger design issue with the API: Is there any point in creating a `SameDocumentTransition` without preparing it?

We could avoid this issue altogether with a design like this:

```js
const transition = document.stateTransition({
  async updateState() {
    // Perform the DOM update
    // (like our prepare callback)
  },
});

await transition.ready;
// Pseudos and animations are created
await transition.finished;
// Transition is complete

// transition.abandon() also exists
```

**Comment by jakearchibald** [comment]
Copying over a comment by @khushalsagar from https://github.com/tabatkins/specs/pull/89#discussion_r937154280

---

Just to make sure, (the spec change in https://github.com/tabatkins/specs/pull/89) implies that a SameDocumentTransition is not reusable.  @vmpstr and I were discussing how to handle all the edge cases where there can be an error or a new transition while there is already an ongoing one and he made one argument for why its simpler to not allow reuse (its in the summary below).

Let's go through all the async points. What to do if we get another transition request at any of these points or there is an error.

1) prepare is called and we're waiting for the next rAF. This transition can't have an error but what to do if we get another prepare call (from a different transition object). The options are:

    - Add the previous callback to an ordered list. Assume that the transition is from current DOM to the state after executing all callbacks. So when capture finishes, all these callbacks will be executed serially to generate the incoming DOM.
    - Add the previous callback to an ordered list. Assume that the transition is from DOM after all pending callbacks. So execute all of them serially, rejecting promises and then start the capture phase. The latest callback runs to get the incoming DOM after capture is done.

1) At the next rAF we realize constraints are not satisfied so the transition needs to be aborted. I don't think we should suppress rendering in this case. So we can dispatch the callback, wait for it to finish and then reject promises. This would be equivalent to the developer synchronously updating the DOM without the feature.

2) We've issued an operation to capture snapshots and the operation fails. We immediately unblock rendering, tear down the pseudo DOM and dispatch the callback followed by resolving promises.

    If we get another prepare while we're waiting for the previous snapshot request to be serviced, then again we either assume transition is from the snapshotted state to the version after the final callback. So we add this prepare to the list that gets executed when the snapshot is done. Or abort the transition by unsuppressing rendering and executing all the pending callbacks. Then do another capture request and the transition continues as usual.

3) The snapshot operation is finished and the callback has been dispatched, we're waiting for it to resolve. If we get a prepares at this step, either assume transition is from currently snapshotted state to the version after the latest prepare. So add this to pending prepare callbacks and the transition starts once all the pending ones have finished executing.

    Or abort by unsupressing rendering and wait for the invoked callback to finish. The new PrepareCallback is the incoming DOM candidate. If we get another prepare in this state, add the current candidate to the list and update the incoming DOM candidate. Once all pending callbacks are done, capture begins and transition continues as usual.

4) The callback for the incoming DOM has resolved but the incoming DOM doesn't satisfy the constraints for the transition. Stop suppressing rendering and abandon the transition.

At any point, if a SameDocumentTransition object gets an abandon() call we can skip running the callback assuming that's what the dev wants. This way if the next prepare intentionally wants to abort the previous one, devs can call abandon on it. This is easier to reason about if we don't make the objects reusable.

**Comment by khushalsagar** [comment]
We decided to not allow them to be reusable and its enforced in the spec text.

@jakearchibald did you still want to use this issue to track switching from a ctor to document.startTransition(..) so getting an object is coupled with starting a transition? Our last discussion was about both making sense, Animation allows you to construct and pass the object to lazily start the animation. I'm ok with the current ctor option and adding something like this later if needed.

**Comment by jakearchibald** [comment]
I'll roll it into https://github.com/WICG/shared-element-transitions/issues/175
