### ISSUE TITLE
If one transition calls prepare() before another finishes, which one aborts/fails?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#174]
In the current implementation, the new transition will fail.

I think we should abandon the old one in favour of the new one. This better matches most navigations, where if you click one link, then another, the former navigation is abandoned in favour of the latter.

**Comment by jods4** [comment]
Would be nice if the API supported multiple concurrent animations, that would enable scenarios where it's used to transitions states of sub-parts of the page (like widgets).

E.g. a tab control on a page could use it to animate going from one page to the next, same for a carousel control animating its position.
If both are present on the page, they should be able to animate their contents independently.

**Comment by jakearchibald** [comment]
@jods4 agreed. This is being discussed in https://github.com/WICG/shared-element-transitions/issues/52.

To clarify, this issue is about two transitions that cannot happen concurrently.

**Comment by khushalsagar** [comment]
Closely related to the broader issue for dealing with concurrent transition requests discussed in #175.

**Comment by khushalsagar** [comment]
Addressed in https://github.com/tabatkins/specs/pull/97.
