### ISSUE TITLE
is it possible to change the background colour behind transitions?

### ISSUE THREAD

**Issue by gavJackson** [WICG/shared-element-transitions#192]
I spent a work hackathon day experimenting with adding it to our app and was largely successful although I couldn't work out how to change the colour behind the transitions.  

I have background-color and background gradients styles on the html, body and my low level DOM nodes but whatever I try I still get a white background behind the transitions.  This isn't too bad on light skins, but we also have a dark mode and it looks pretty jarring then, is there something simple I am missing? or is this something else that needs adding to the spec? I even tried adding a background colour to the psuedo page transition elements.  This image shows what I mean:

<img width="1028" alt="Screenshot 2022-09-13 at 08 59 22" src="https://user-images.githubusercontent.com/164279/189844924-79205ab0-d6a0-4914-ab1c-de01d5b9c320.png">

p.s. I am blown away by this API, its very cool! a couple of years ago i tried implementing my own screenshot capturing transition system...not easy! I totally appreciate this, especially the DOM flattening.

**Comment by jakearchibald** [comment]
Glad you had fun with the API!

For the background colour, did you try:

```css
::page-transition {
  background: black;
}
```

**Comment by gavJackson** [comment]
amazing thanks, that got it - much appreciated
