### ISSUE TITLE
Feature Request: Add easing to the element transition

### ISSUE THREAD

**Issue by uskay** [WICG/shared-element-transitions#20]
Per the material design guidelines, smooth speed adjustments cannot be done just by stating the duration but easing takes an important role: https://material.io/design/motion/speed.html#easing

**Can we consider adding a parameter for setting the easing to the element transition?**

Example:

```javascript
document.documentTransition.prepare({
    rootTransition: 'reveal-left',
    duration: 300,
    timingFunction: 'ease-in'
})
```

The value of the `timingFunction` can be similar to the CSS [transition-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function), including the option to state custom `cubic-bezier`.

- `ease`
- `ease-in`
- `ease-out`
- `ease-in-out`
- `linear`
- `cubic-bezier(x1,y1,x2,y2)`
- and such

**Comment by Link2Twenty** [comment]
I don't think css style cubic-bezier can be used anywhere else in JS, this is not a for or against just an observation.

**Comment by vmpstr** [comment]
I think our intent is to not expose these type of controls unless absolutely necessary. I'm going to close for now, but if we have specific cases where such controls are very important, please do reopen.
