### ISSUE TITLE
Define root transitions as separate single element transitions. 

### ISSUE THREAD

**Issue by andreban** [WICG/shared-element-transitions#31]
Hi everyone,

Coming from an Android background, one thing that I missed while trying out the API is the ability to set different enter/exit animations. What this allows is for the developer to specify an "exit" animation from the page being removed and an "enter" animation for the new page.

Developers can then combine different transitions:
 - current page exits with a "fade-out" animation, and the new page enters with a "slide-in";
 - current page exits with a "slide-out" animation, and the new page enters with a "slide-in",
 - and so on...

Something like:
```js
function handleTransition() {
  document.documentTransition.prepare({
    rootEnterTransition: {
       exitAnimation: "slide-out-right",
       enterAnimation: "reveal-left",
    },
  }).then(() => {
    changeBodyBackground();
    document.documentTransition.start().then(() => console.log("transition finished"));
  });
}
```

Looking forward to hearing thoughts on this.

**Comment by jakearchibald** [comment]
I agree this is currently missing the ability to animate both the incoming and outgoing page.

Even at a basic level, 'slide' animations tend to involve moving both, but that doesn't seem to be an option with the current implementation.

**Comment by khushalsagar** [comment]
This sounds completely reasonable to me. The idea of entry/exit transitions for shared elements is being discussed in #37. I'll repurpose this issue to discuss the idea of defining root transitions similar to an entry/exit shared element transition. I think that also makes it easy to customize them as mentioned in #28 going forward.

**Comment by khushalsagar** [comment]
Discussed this recently and agreed that expressing root transitions as 2 enter/exit animations is a good idea. One detail to figure out is what the background should be when drawing the root elements. The current patterns were setup such that this was not an issue, either the old or new root completely covers the viewport and is opaque.

**Comment by khushalsagar** [comment]
The latest API supports this.
