### ISSUE TITLE
Demo & analysis: SPA tabs of TODO lists

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#51]
https://static-misc-3.glitch.me/todo-list-transitions/ - it's a bit of a nonsense demo, but useful for kicking the tyres.

It's based on https://svelte.dev/examples#animate from @Rich-Harris, but I threw in some tabs to also play around with `appHistory`.

Thoughts:

## Tabs

`appHistory` seems to work well! @dominic, am I using it as intended? Source: https://glitch.com/edit/#!/static-misc-3?path=todo-list-transitions%2Fscript.js%3A20%3A9.

I wanted to do a transition where the outgoing tab content slides left and the incoming tab content slides in from the right, while cross-fading (and the reverse when using the back button). That isn't possible, so I got a close as I could using a root transition. Using a root transition feels like a hack here, because now I have to make _everything else_ shared, so it isn't included in the transition (I left the top heading alone to highlight the issue).

For instance, I don't really want the tabs to cross-fade, I'd rather they changed instantly so it feels responsive. Ideally, I'd like the whole transition to be scoped to the tab content only.

## todo items

Ticking/unticking todo items is janky. It feels kinda janky with devtools closed, even more janky with devtools open. But here's the fun bit, it's super-smooth during a performance timeline recording. 🙃 

I'm still seeing a fading glitch. It's most noticeable on done todo items. I can take a screen recording if you can't see it.

I'd have preferred the item swapping sides to be on top in terms of z-index, but I couldn't figure out how to do this.

Aside from the jankyness, the easing doesn't feel right for this particular transition, but I can't control that.

Deleting items works pretty well, but I'd have liked to be able to control how it transitions away, eg by scaling away.

**Comment by khushalsagar** [comment]
I filed bug about the flicker at the end of the tabs animation (crbug.com/1247678). That looks like an implementation bug. The feature request to have the transition scoped to just the tabs content makes sense (covered in #37).

I didn't fine the todo items animation janky or glitchy though. It's unfortunate it doesn't repro if you're tracing (and also very surprising). The easiest way to debug these issues is with a chromium trace. Can you check on the latest canary (that's where I tested). And if you're still seeing jank, then please file a crbug with the chrome version. I'd also suggest filing a trace (even if it doesn't repro with it). We'll at least be able to see what rendering path is being used to rule out ongoing experiments.

I also couldn't see a fading glitch. Chrome canary has an option to slow down the animation now (documentTransition API Duration Control) that I was using to observe it.

The z-index issue is an excellent one. It's being tracked in #23 and this is good input for it.

Regarding customizing the transition, #28 and #9 are discussing that. The low level customization would let you provide explicit values for the end transform and coordinate the timing with a fade out. It also makes sense to have some high level common patterns in the API (like implode for scaling away and clip-reveal for what also mentioned in #49).

**Comment by jakearchibald** [comment]
Here's a trace I took while the animation was janky: [trace_Thu_Sep_09_2021_11.44.43.json.gz](https://github.com/WICG/shared-element-transitions/files/7135845/trace_Thu_Sep_09_2021_11.44.43.json.gz).

**Comment by jakearchibald** [comment]
https://www.youtube.com/watch?v=v-TXXU-VoAA here's a screencase that shows the jank and the colour change (most noticeable on the green which briefly loses saturation)

**Comment by khushalsagar** [comment]
I think both these issues have been resolved now.

**Comment by jakearchibald** [comment]
Yeah, the slowness was probably due to isolation.
