### ISSUE TITLE
Decide how to reference elements across Documents for transitions.

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#59]
A common theme across multiple issues has been how to reference elements which a Document doesn't have access to. This is required since irrespective of whether we have a largely script or declarative API, the animation concepts like paired animations (#56) would have to be declared by one Document and reference elements in another Document.

The proposal [here](https://github.com/WICG/shared-element-transitions/blob/main/feature_details.md#referencing-elements) side-stepped it by adding placeholder for the previous Document's elements and using direct references from the new Document's elements.

But the above still misses a use-case that has come up : animating elements which exist in a nested frame. The embedding frame has no way to get references to elements within the nested frame. So a script based API would still need some type of element identifier.

@jakearchibald @chrishtr FYI.

**Comment by vmpstr** [comment]
Do we have use-cases for transitioning an element from the embedding frame into the embedded one?

From my understanding, a common pattern would be to either transition the frame to a different object or to transition objects within a frame (which can be orchestrated by the frame script). 

I think having the ability to references elements in a third party document is great (probably via something like CSS selectors), but then if we can easily do this do we also want to consider having the outgoing page be responsible for setting up the transition in MPA cases

**Comment by khushalsagar** [comment]
The use-case which inspired this discussion, crossing frame boundaries in the context of one transition, came because of AMP (#54). The outgoing page would need to be able to reference elements within the incoming page's iframe element's Document for this to work.

I think the idea of the outgoing page setting up the transition for MPA is orthogonal to the referencing elements discussion. That's required for the use-cases highlighted in #25.

**Comment by vmpstr** [comment]
Just to clarify, are we talking about third-party iframes?

I understand that AMP is set up as a full screen iframe, but it feels like this type of a scenario opens the door for some strange transitions: page A navigates and animates its elements into the (cross-origin?) iframe of page B. So I can share elements with an ad maybe.

I guess if this can be solved, we can also let the embedding destination page have some control over what to allow or disallow

**Comment by khushalsagar** [comment]
Yeah, it is about third-party iframes. And it is indeed the case that AMP uses a fullscreen iframe but don't want to design with that assumption. We want to think through a model where the incoming/outgoing page can involve shared elements from embedded iframes. Let's move the discussion into a separate issue. It seems like we need to clarify the exact feature request (#61).

**Comment by khushalsagar** [comment]
Works using page-transition-tag to reference elements across docs.
