### ISSUE TITLE
Explain cached snapshots for transitions and associated constraints.

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#60]
We need to clarify what representation of shared elements is cached by the browser, the constraints it brings in terms of retaining the element's old visual state and the properties on it which can be interpolated.

The animations specified by a transition are executed on the same representation except in the case of new DOM, which is live, this representation could update every frame from mutations outside the transition animations. For example the frame changing in case of animated GIFs.

**Comment by vmpstr** [comment]
Is the agreement that the 'old' state is a pixel representation that does not have any raster inducing changes to it, and the 'new' state is live DOM so it has all of the animations / raster changes?

**Comment by khushalsagar** [comment]
Clarified in the spec.
