### ISSUE TITLE
Interaction with the fullscreen API

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#68]
The fullscreen API takes an element and renders it on some top layer. Shared element transitions do a similar-but-different thing, so we need to figure out how they interact.

This is less of a problem for cross-document transitions, as we always break out of full-screen in those cases, but we still need to define how elements are captured then we're in the fullscreen state.

I haven't fully thought through it, but here are some questions it raises:

- When we capture an element within a fullscreen'd element, do we capture it in its fullscreen state?
- What happens when a captured element is outside of the fullscreen'd element?
- What if the current fullscreen'd element is within a cross-origin iframe? The element may assume that another origin cannot draw on top. If that's the case we need to ensure SET doesn't change that.

**Comment by khushalsagar** [comment]
We are creating a new stacking context which is a sibling of the stacking context for root and top layer elements. This allows elements in the top layer to be snapshotted and displayed the same as regular elements.
