### ISSUE TITLE
Should we be able to expand root capture area

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#72]
For cases like vertical movement, should we have the ability to expand how much area is captured by the 'offer up' phase

**Comment by khushalsagar** [comment]
Yes, we should definitely be able to expand the root capture area. But I think this can be punted to v2. Similar to how we want to support overflow for shared element content eventually.

**Comment by vmpstr** [comment]
I'm fine with punting. I think the only downside here is that vertical movement on typical pages may seem less polished due to being cut-off at viewport bounds.

**Comment by khushalsagar** [comment]
Agreed, if the animation is going to expose previously hidden content then you need this. I'm totally onboard with this being a legit use-case, just don't think it needs to be MVP blocking.

**Comment by jakearchibald** [comment]
Some overlap with https://github.com/WICG/shared-element-transitions/issues/73 and https://github.com/WICG/shared-element-transitions/issues/85 - if clipping isn't limited to root elements, then we'd need a way to expand those too.

> just don't think it needs to be MVP blocking.

Agreed.

**Comment by khushalsagar** [comment]
Based on the discussion in #73, sounds like we can treat the root similar to other massive elements. Instead of clipping to viewport bounds, capture up to some max bounds.

**Comment by flackr** [comment]
Not sure if this is the same use case, but the [spec](https://www.w3.org/TR/css-contain-2/#using-cv-auto) for `content-visibility: auto` refers to whether an element is [relevant to the user](https://www.w3.org/TR/css-contain-2/#relevant-to-the-user) based on intersection with a user-agent defined margin around the viewport. We could use this same margin for the portion of offscreen content which should be available.

**Comment by khushalsagar** [comment]
Do you mean have the capped size for capture be ~viewport bounds + margin?

The discussion on #73 is leaning towards keeping the amount of content captured (capped size) independent of where the element is with respect to the viewport. The latter only influences which subset of the element is captured. We could have the capped size be a function of viewport bounds though.

**Comment by khushalsagar** [comment]
The conclusion for this was to avoid a different behaviour between root and non-root elements. So the area captured for the root image is computed similar to the strategy for non-root elements discussed in #73.
