### ISSUE TITLE
How does the UA style the new pseudo elements?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#75]
From the explainer:

Open question: How does the UA apply styles to these elements? Particularly styles which are specific to one transition element, such as its transform. Inline styles are simple, but tricky for a developer to override in a stylesheet. An alternative would be to generate a `<style>` and put it, and the transition elements, in a shadow root along with the transition elements.

**Comment by khushalsagar** [comment]
This is a bit tied to #93. Assuming we use a shadow DOM, we can set the style using a <style> element in the shadow root and developer provides styles will override this.

But I'm not sure how to enable developers to add animations on top of what the UA is adding using computed state (like transform). For example assuming the UA adds the following default animation on the container element for size/transform using a CSS animation :

```
/* Cached values from old page */
@keyframes size-and-transform {
  from {
    width:
    height:
    transform:
  }
}

foo {
  animation: size-and-transform 0.25s;
}
```

The developer can override the animation but can they add one on top of size-and-transform?

**Comment by jakearchibald** [comment]
If we're not going with shadow-dom, which seems to be the case, I guess we just define this as a UA stylesheet that gets mutated. It's new, but doesn't seem too scary.

**Comment by khushalsagar** [comment]
+1. This will a UA stylesheet that can be overridden by developer stylesheets. The cascade for it is already spec'd here : https://www.w3.org/TR/CSS21/cascade.html#cascade

**Comment by jakearchibald** [comment]
It's a little different in that the stylesheet is mutated and therefore becomes different per page. But that seems ok.

**Comment by khushalsagar** [comment]
Yeah, mutating the stylesheet is the new thing. I'm actually implementing this right now and hopefully no issues. :)

**Comment by khushalsagar** [comment]
Dynamic UA stylesheet has been implemented.
