### ISSUE TITLE
How do new elements in top layer interact with other top layer elements

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#76]
... such as fullscreen and `<dialog>`

Related: #68

**Comment by khushalsagar** [comment]
Assuming we go with the approach in #92, having an element in the top layer won't be any different. If an element in the top layer is a shared element, then its snapshot would be as it was painted when in the top layer.

**Comment by khushalsagar** [comment]
With the resolution in #92, the new elements or transition DOM will not be painted in the top layer. So there is no interaction with other elements in top layer to worry about.

Also, having an element in top layer doesn't affect whether it can be used as a shared element.
