### ISSUE TITLE
Is the tight coupling with the app-history API necessary

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#77]
From the explainer:
```js
// In Page-A
addEventListener('navigate', (event) => {
  event.prepareSameOriginPageTransition((transition) => {
    transition.offerElement('header', document.querySelector('.header'), {
      capture: 'container-and-child',
    });

    transition.setData({…});
  });
});
```

The `prepareSameOriginPageTransition` is a function on the navigate event

**Comment by khushalsagar** [comment]
My motivation to avoid the dependency on app-history is that it is also a new API. It might be adopted by browsers at a different cadence and with a tight coupling like this, a browser must ship app-history to support transitions. It also doesn't seem like the dependency is necessary.

The way I see it, the dependency on the "navigate" event here is for 2 things :

1) For the developer to observe a navigation.
2) To associate the data passed to the transition object (set of offered elements and context in setData) with a particular navigation.

1) could be done using existing APIs. And for 2) we could have the "transition" object take a URL string which specifies which navigations the data is for or just say that it applies to the next navigation? Something like :

```js
function setUpTransitionToFoo() {
  document.documentTransition.offerElement('header', document.querySelector('.header'), {
      capture: 'container-and-child',
    });
  document.documentTransition.setData(...);
}
```

```html
<a href="foo.com" onclick="setUpTransitionToFoo()"></a>
```

I'm not opposed to depending on app-history if working around it will result in a bad API. And perhaps my motivation is not as concerning. But figured it's worth discussing.

**Comment by flackr** [comment]
Maybe we should consider an API that would allow these transitions for non-navigation use cases? The ability to cross fade between element contents efficiently is a novel one that could be useful more generally. I'm not sure exactly what that API would look like - we would still need some pieces of it for transferring the offered elements between pages but the set up and running of the transitions could be scheduled anytime.

**Comment by jakearchibald** [comment]
How would that differ from the SPA API?

**Comment by khushalsagar** [comment]
@flackr we do intent to have the SPA API be disjoint from any navigation aspects. It'll be similar to how the prepare API currently is analogous to a navigation in the MPA case. So this issue is primarily for having offered elements/data in the script API during an MPA nav be association with a particular navigation.

In the SPA case, this state will be associated with a particular transition because we'll have an API like prepare which will initiate the transition.

**Comment by khushalsagar** [comment]
The conclusion here was that its a worthwhile goal to decouple from app-history. But we'll revisit this as the API proposal shapes up and it becomes clear how difficult it is to design the API without the dependency.
