### ISSUE TITLE
Is `offerElement` API necessary?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#78]
From the explainer:
```js
// In Page-A
addEventListener('navigate', (event) => {
  event.prepareSameOriginPageTransition((transition) => {
    transition.offerElement('header', document.querySelector('.header'), {
      capture: 'container-and-child',
    });

    transition.setData({…});
  });
});
```

Do we need `offerElement`? The same thing could be done by adding the CSS properties.

**Comment by jakearchibald** [comment]
This is very similar to https://github.com/WICG/shared-element-transitions/issues/79.

It might seem like less of a problem here, since the page is outgoing, but bfcache is a thing, so it's kinda the same.

**Comment by khushalsagar** [comment]
Resolved in the latest API, all JS tagging builds on top of the CSS API.
