### ISSUE TITLE
Is `createTransitionElement` necessary?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#79]
From the explainer:

```js
// In Page-B
document.performTransition((transition) => {
  console.log(transition.data);
  const pageAHeader = transition.offeredElements.get('header');
  const pageBHeader = transition.createTransitionElement(document.querySelector('.header'), {
    capture: 'container-and-child',
  });
  transition.matchElements(pageAHeader, pageBHeader);
});
```

Do we need `createTransitionElement`? It could be done via adding CSS properties, but it might be clumsy if the developer is going to immediately remove the properties afterwards.

**Comment by jakearchibald** [comment]
To expand on what I mean by "clumsy":

It could be common to have different transitions depending on the source and destination of the transition. I'm not sure if this will be possible with pure CSS, but the JS API will allow it.

So the situation is: The incoming page identifies that the previous page was "the preferences page", and the transition to this page should be different. Eg, the "preferences" page is conceptually layered on top of the new page, whereas other transitions are conceptually adjacent.

This means a different set of elements need to be prepared for this transition. If they add styles for this one-off action, they'll need to remove them after the transition, else there'll still be there when the new page wants to transition away.

Is that clumsy enough to warrant an API to select elements "for this transition only", avoiding the need to remove the styles afterwards?

**Comment by jakearchibald** [comment]
It's also worth considering https://github.com/WICG/shared-element-transitions/issues/61 here, as I'm not sure how that would work with CSS.

**Comment by khushalsagar** [comment]
Resolved to change the pageTransitionTag style in JS to do this in the latest API.
