### ISSUE TITLE
When does the default animation start?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#83]
Does it happen when first render of Page-B would happen?

**Comment by vmpstr** [comment]
The animation has to begin before we present the first frame of the new page. I think it's fine to start the animation right when we would have presented the first frame. Then we can rely on render blocking attributes given by developers to ensure that this first frame doesn't happen too soon. 

I suspect it will be easy to create a bad experience if the developer wants to wait for some large image to load, but that would be more of a problem of supporting render blocking on things like large images.

**Comment by khushalsagar** [comment]
+1 to what Vlad said. And good point about avoiding the load being blocked on an image. The render-blocking proposal talks about a UA defined timeout for how long we block on a resource to avoid footguns like this. There is a suggestion to let developers configure this timeout but the first version leaves it to the UA.

**Comment by daKmoR** [comment]
This question is still "marked" as open in the explainer?

https://github.com/WICG/shared-element-transitions/blob/main/explainer.md#:~:text=Open%20question%3A%20When%20will%20the%20default%20animation%20start%3F%20When%20the%20browser%20would%20usually%20first%20render%20Page%2DB%3F

should this question be removed in the explainer?

**Comment by khushalsagar** [comment]
Yeah, here is a PR to update the explainer : https://github.com/WICG/shared-element-transitions/pull/135/files
