### ISSUE TITLE
What's the deadline for calling `performTransition`?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#86]
Can't wait too long, but when exactly is the cut-off point?

**Comment by jakearchibald** [comment]
I think we'd have a hard time pushing back first paint for sites that don't want to perform a transition, so I guess that makes the deadline "first paint".

**Comment by khushalsagar** [comment]
The spec leaves this up to the UA in the SPA API. In the MPA case, this is dependent on a UA defined timeout for render blocking.
