### ISSUE TITLE
Is ability to have a different DOM depending on the transition intentional?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#87]
From the explainer, when talking about the alternative of using Shadow DOM:

```js
// In Page-B
document.performTransition((transition) => {
  // Build up transition parts, then…
  transition.root.querySelector('[part=header]').animate(…);
});
```

If the 'stage' of the transition is exposed as a shadow root like this, the developer can interact with the elements in a regular way. The developer could even create elements specifically for the transition.

Open question: Is the freedom above a feature or a bug?

**Comment by jakearchibald** [comment]
It feels like the shadow DOM idea is a no-go. I still think it's nice to be able to add elements specifically for the transition, but I guess we could look at other ways to do that later.

**Comment by khushalsagar** [comment]
Resolving this now since we decided to use pseudo-elements for the transition DOM.
