### ISSUE TITLE
Should hit-testing ignore transition elements?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#88]
We should ignore anything that doesn't hit transition elements, since root can be in a partially transitioned state. What about the elements themselves?

**Comment by jakearchibald** [comment]
My assumption was that the transition root would stop the propagation of any events.

The elements themselves would have `pointer-events: none`. I guess developers could override that, but it wouldn't be useful.

**Comment by vmpstr** [comment]
I agree that we would need to stop the propagation of any events since it would propagate to the wrong spot.

The alternative is for the live snapshot to fire the hit-testing events within the source element in the DOM. IOW, with a lot of work it theoretically is possible to hit test live snapshots, but I agree with Jake that it's probably not that important to do.

**Comment by khushalsagar** [comment]
> The alternative is for the live snapshot to fire the hit-testing events within the source element in the DOM.

But we also have snapshots for which there isn't a source element in the actual DOM...

> My assumption was that the transition root would stop the propagation of any events

Does that mean we're suppressing input completely or that the developer can still observe them via the documentElement. For example adding an onclick handler to it. There just won't be any propagation of the event past the root element.

**Comment by jakearchibald** [comment]
We might need to be much stricter about this in the cross-origin case, since the x/y of clicks the user makes on data from another origin can be a privacy/security leak.

**Comment by khushalsagar** [comment]
Oh yeah, this whole discussion is limited to same-origin. For cross-origin the transition is happening on the incoming page and it can't even know about the transition. So we'll completely disable input there.

There is actually precedent for the above with paint holding and I think we drop input even before doing hit testing. Will look up where that code is.

**Comment by khushalsagar** [comment]
This [spec edit](https://github.com/tabatkins/specs/pull/94) takes care of this issue. We skip hit testing any shared element (including the root if its tagged) similar to what content-visibility does. But the pseudo DOM created for the transition receives input and does hit-testing same as regular DOM.

There is a follow up to provide an API that would allow a dev to map an event from page-transition-incoming-image to the corresponding DOM element but its out of scope for v1.
