### ISSUE TITLE
contain: paint or paint containment

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#96]
The transitioning elements are required to have paint containment in order to be containing blocks (afaik) and limit the amount they paint unless explicitly expanded by `overflow-clip-margin`.

The explainer talks about developer requiring `contain: paint`. I just wanted to clarify whether we're requiring specific `contain: paint` style or any style that ensure paint containment (such as `content-visibility: auto`).

I assume it's the latter

**Comment by jakearchibald** [comment]
Latter works for me.

**Comment by khushalsagar** [comment]
The spec text now states "element does not have [layout containment](https://drafts.csswg.org/css-contain-2/#layout-containment)." which is consistent with latter.
