### ISSUE TITLE
Should visual effects be excluded from the snapshot in "As a single image" mode.

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#97]
"single image" mode bakes visual effects inherited by a descendent into the snapshot, similar to [element()](https://developer.mozilla.org/en-US/docs/Web/CSS/element()). This implies that when we do preserve the hierarchy of shared elements in the transition DOM, only transform/clipping relationship will be preserved. Consider an example like this :

```html
<div style="opacity: 0.5" id = "parent">
      <div id="child">A</div>
</div>
```

which should map to the following pseudo element hierarchy :

```html
<div id="parent_container">
  <div style="content:cached-element(#parent)"></div>
  <div style="content:element(#parent)"></div>
  <div id="child_container">
    <div style="content:cached-element(#child)"></div>
    <div style="content:element(#child)"></div>
  </div>
```

where cached-element is the cached snapshot of an element from the old page. If the opacity is baked into the snapshot instead of being a style on "parent_container", then it won't apply to the descendants even if we preserve the hierarchy.

It would work with "As the element's computed style + content image" mode. So we could either say that the developer must use this mode if they want these effects to continue to apply to descendants. Or the "As a single image" mode could exclude visual effects which apply to descendants (opacity, filter, clip-path, mask) from the snapshot and add them to the container instead.

Even if shared element hierarchy is deferred from v1, we have a similar problem for a filter which is specified on the root element.

**Comment by chrishtr** [comment]
> then it won't apply to the descendants even if we preserve the hierarchy.

Which descendants do you mean here?

**Comment by khushalsagar** [comment]
The descendants in the transition DOM built using pseudo elements. In the example on the first comment, opacity on parent is applied to the text "A" on child.

When we build the transition DOM, this opacity could be painted into element(#parent). In which case it doesn't apply to the child's image in the transition DOM. Or we could not paint into element(#parent) and add it to "parent_container"'s style. In which case it applies to the snapshot from element(#parent) and also child_container.

The same thing applies to the effects on the root element. We could paint into the root snapshot or set up a hierarchy like the above with a container pseudo element created for the root images and descendent container elements for each shared element. The filter can be added to the root container's style instead of being painted into the root image.

**Comment by chrishtr** [comment]
Ah ok. I hadn't looked closely enough at your example sorry. Yes that's right.

I don't think clipping will work either, just transform.

**Comment by khushalsagar** [comment]
Hmmm, yeah. I guess we need to copy the overflow style as well to retain the clipping behaviour?

**Comment by chrishtr** [comment]
I think this is fine and a result of the single image mode. Why not just close this issue as working as intended? If you want to have visual dependencies between the shared elements, use the other mode.

**Comment by khushalsagar** [comment]
That sounds reasonable to me. I opened this primarily because of the discussion in the comment thread [here](https://github.com/WICG/shared-element-transitions/pull/95#discussion_r756296623).

The question was about supporting hierarchy mode for the out of process cross-origin implementation. We can support it but as you mentioned, it will only preserve the transform hierarchy. And supporting the style + image mode there is too difficult.

So we might need a middle ground mode if we wanted visual dependencies/clipping to work in a out of process hierarchy implementation. But we can cross that bridge when we get there.

I'll close this issue. @vmpstr and @ianvollick, please feel to reopen if needed.
